$(document).ready(function(){
    $(".formulario").fadeOut(0)
    $(".iniciar").mouseenter(function(){
        $(".formulario").fadeIn(1000)
    })
    $(".iniciar").mouseleave(function(){
        $(".formulario").fadeOut(1000)
    })
})